name: GitHub Actions Build and Deploy GitHub Page
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up built environment
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - name: Build
      run: |
        npm run build
        node -e "console.log(new Date('Fri, 14 Jan 2022 13:02:12 +0800').getTime()/1000)" > > ./article/testgithubaction.html
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: .
    - name: Deploy
      uses: actions/deploy-pages@v1
